### ISSUE TITLE
Add Codeigniter to PHPGGC

### ISSUE THREAD

**Issue by TheCrott** [ambionics/phpggc#23]
Any plan to add Codeigniter 2.x and 3.x to phpggc?

**Comment by farisv** [comment]
We have obstacles because:
- Default installation of CI doesn't rely much on third party libraries.
- By default, CI doesn't use destruct or wakeup methods. In CI 3.1.9, only `CI_Cache_memcached`, `CI_Cache_redis`, and `CI_Email` use destruct. All is a built-in library and not loaded by default. For example: to load `CI_Cache_redis`, dev need to add `$this->load->driver('cache', ['adapter'=>'redis']);` inside the controller.

So for CI, we rely on what libraries are loaded (third-party or built-in). I check for all built-in library in CI, we can create gadgets chain for SQL Injection with `CI_Cache_redis` and `CI_Session_database_driver` but remember, both are not loaded by default.

**Comment by cfreal** [comment]
Yeah, sadly there's absolutely no way we get anything interesting from CI 2/3.
