### ISSUE TITLE
Refactor to Symfony Console

### ISSUE THREAD

**Issue by mpchadwick** [ambionics/phpggc#47]
I'm opening an issue to evaluate the idea of this project being migrated to be built on top of Symfony Console.

https://symfony.com/doc/current/components/console.html

Symfony Console is the de facto framework for PHP CLI apps used by the likes of:

- [Composer](https://github.com/composer/composer/blob/4441be1a0536789b28bea20c3a86cbcac852a0d2/composer.json#L34)
- [Magento](https://github.com/magento/magento2/blob/4f6c78e81b3d91947287094316682461b06d372f/composer.json#L50)
- [Drupal](https://github.com/drush-ops/drush/blob/f9197ddf9509cfbfd974ea3708aa4dc293ff4c86/composer.json#L49)

A couple advantages that immediately come to mind:

- Many PHP developers have seen and worked with Symfony Console apps before. This potentially lowers the barrier to entry for new users
- Assuming we move forward with test coverage (see #46) Symfony Console includes a framework for running tests on commands (https://symfony.com/doc/current/console.html#testing-commands)

Thoughts?

**Comment by proclnas** [comment]
I agree with the advantages. It would give even greater robustness to the project (-:

**Comment by cfreal** [comment]
Hello Max,

The two issues you brought up were on my mind for some time.

What I'm afraid of with composer packages are dependencies: I want PHPGGC to **run in the minimal PHP environment**: you install php-cli, you `git pull` PHPGGC, and it works.
Therefore, any packagist dependency I add, I need it to be included in PHPGGC. No `composer install` required. No `apt install php-libxml` required. Straight up works.

`symfony/console` actually looks like a good candidate since it has only a few dependencies and no PHP extensions requirements.

It'd be great to get input from other people on this.

**Comment by cfreal** [comment]
Closing for now.
