### ISSUE TITLE
Gadget for symfony/config ^3.4

### ISSUE THREAD

**Issue by Gguerry** [ambionics/phpggc#53]
Hey!

Cool project, I found it by accident while looking at deserializations in PHP. I'm trying to exploit a vulnerable application where the changelog is like this:

>      $referer = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
>      if (is_numeric($what)) {
>      if (ctype_digit($what)) {
>          $zones = OA_cacheGetPublisherZones($what);
>          $nz = false;
>      } else {
>          $zones = unserialize($what);
>          parse_str($what, $zones);
>          $nz = true;
>      }

And the dependencies are:

>  "require": {
>          "symfony/config": "^3.4",
>          "symfony/dependency-injection": "^3.4",
>          "league/flysystem": "^1.0",
>          "league/flysystem-ziparchive": "^1.0",

>          "sinergi/browser-detector": "^6.0",
>          "jeremykendall/php-domain-parser": "~2.0",

>          "figdice/asseteer": "dev-master",
>          "tinymce/tinymce": "^4.6"
>      },
>      "require-dev": {
>          "symfony/finder": "^3.4"
>      },

I'm able to confirm the vulnerability by using stdClass and echo data back, however none of the gadgets appears to support my target. The closest RCE version is Symfony/RCE1, I tried like:

> php phpggc Symfony/RCE1 /bin/ls 
> php phpggc Symfony/RCE1 /bin/ls -f
> php phpggc Symfony/RCE1 /bin/ls -f -s
> php phpggc Symfony/RCE1 /bin/ls -s

And nothing is returned. The gadget for Symfony/FW2 appears to support the same version, however it's file write and I don't know the DocumentRoot path and neither if it will work - I guess it's blind.

Am i missing anything? Any suggestion?

ps: I checked your nice blogpost (https://www.ambionics.io/blog/php-generic-gadget-chains), good work.

Thanks.

**Comment by cfreal** [comment]
Here's what I'd do in your case:
- Since you seem to have the composer.json file, copy it to a local directory, `/tmp/test` for instance.
- run `composer install`.
- use  ̀php /path/to/phpggc Symfony/RCE1 /bin/ls --test-payload` in the `/tmp/test` directory. `--test-payload` will just unserialize the payload in the current context. If you don't get any output, well, that means you lost. Try with FW2. Doesn't work either ? Well, you're out of luck.

I did just that on my computer, with the composer.json file you provided. It does not seem to work. Here's why:
- RCE1 requires `Symfony\Component\Cache\Adapter\AcpuAdapter`, which is not present
- FW2 requires `Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait` which is not present.

Sorry friend, you'll have to either find your own gadget chain, or find another way.

Side note: Generally, FileWrite payloads do not require a full path ! Just use `./shell.php` for instance.
